package com.wtgroup.blog.mapper;

import com.wtgroup.blog.entity.TResource;
import com.wtgroup.blog.entity.TResourceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    int countByExample(TResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    int deleteByExample(TResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    int insert(TResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    int insertSelective(TResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    List<TResource> selectByExample(TResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    TResource selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    int updateByExampleSelective(@Param("record") TResource record, @Param("example") TResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    int updateByExample(@Param("record") TResource record, @Param("example") TResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    int updateByPrimaryKeySelective(TResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    int updateByPrimaryKey(TResource record);
}