package com.wtgroup.blog.mapper;

import com.wtgroup.blog.entity.TUserLog;
import com.wtgroup.blog.entity.TUserLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TUserLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_log
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    int countByExample(TUserLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_log
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    int deleteByExample(TUserLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_log
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_log
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    int insert(TUserLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_log
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    int insertSelective(TUserLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_log
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    List<TUserLog> selectByExample(TUserLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_log
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    TUserLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_log
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    int updateByExampleSelective(@Param("record") TUserLog record, @Param("example") TUserLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_log
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    int updateByExample(@Param("record") TUserLog record, @Param("example") TUserLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_log
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    int updateByPrimaryKeySelective(TUserLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_log
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    int updateByPrimaryKey(TUserLog record);
}