package com.wtgroup.blog.entity;

public class TParam {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_param.id
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_param.param_name
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    private String paramName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_param.param_value
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    private String paramValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_param.create_user
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    private Long createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_param.create_time
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    private Long createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_param.update_user
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    private Long updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_param.update_time
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    private Long updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_param.id
     *
     * @return the value of t_param.id
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_param.id
     *
     * @param id the value for t_param.id
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_param.param_name
     *
     * @return the value of t_param.param_name
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    public String getParamName() {
        return paramName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_param.param_name
     *
     * @param paramName the value for t_param.param_name
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    public void setParamName(String paramName) {
        this.paramName = paramName == null ? null : paramName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_param.param_value
     *
     * @return the value of t_param.param_value
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    public String getParamValue() {
        return paramValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_param.param_value
     *
     * @param paramValue the value for t_param.param_value
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    public void setParamValue(String paramValue) {
        this.paramValue = paramValue == null ? null : paramValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_param.create_user
     *
     * @return the value of t_param.create_user
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    public Long getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_param.create_user
     *
     * @param createUser the value for t_param.create_user
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    public void setCreateUser(Long createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_param.create_time
     *
     * @return the value of t_param.create_time
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_param.create_time
     *
     * @param createTime the value for t_param.create_time
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_param.update_user
     *
     * @return the value of t_param.update_user
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    public Long getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_param.update_user
     *
     * @param updateUser the value for t_param.update_user
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    public void setUpdateUser(Long updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_param.update_time
     *
     * @return the value of t_param.update_time
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    public Long getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_param.update_time
     *
     * @param updateTime the value for t_param.update_time
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    public void setUpdateTime(Long updateTime) {
        this.updateTime = updateTime;
    }
}