package com.wtgroup.blog.entity;

import java.util.Date;

public class TUserLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_log.id
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_log.user_id
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_log.login_time
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    private Date loginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_log.login_stat
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    private Integer loginStat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_log.login_error_count
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    private Integer loginErrorCount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_log.id
     *
     * @return the value of t_user_log.id
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_log.id
     *
     * @param id the value for t_user_log.id
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_log.user_id
     *
     * @return the value of t_user_log.user_id
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_log.user_id
     *
     * @param userId the value for t_user_log.user_id
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_log.login_time
     *
     * @return the value of t_user_log.login_time
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    public Date getLoginTime() {
        return loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_log.login_time
     *
     * @param loginTime the value for t_user_log.login_time
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    public void setLoginTime(Date loginTime) {
        this.loginTime = loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_log.login_stat
     *
     * @return the value of t_user_log.login_stat
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    public Integer getLoginStat() {
        return loginStat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_log.login_stat
     *
     * @param loginStat the value for t_user_log.login_stat
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    public void setLoginStat(Integer loginStat) {
        this.loginStat = loginStat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_log.login_error_count
     *
     * @return the value of t_user_log.login_error_count
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    public Integer getLoginErrorCount() {
        return loginErrorCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_log.login_error_count
     *
     * @param loginErrorCount the value for t_user_log.login_error_count
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    public void setLoginErrorCount(Integer loginErrorCount) {
        this.loginErrorCount = loginErrorCount;
    }
}