package com.wtgroup.blog.mapper;

import com.wtgroup.blog.entity.TCategory;
import com.wtgroup.blog.entity.TCategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_category
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    int countByExample(TCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_category
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    int deleteByExample(TCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_category
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_category
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    int insert(TCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_category
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    int insertSelective(TCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_category
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    List<TCategory> selectByExample(TCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_category
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    TCategory selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_category
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    int updateByExampleSelective(@Param("record") TCategory record, @Param("example") TCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_category
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    int updateByExample(@Param("record") TCategory record, @Param("example") TCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_category
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    int updateByPrimaryKeySelective(TCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_category
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    int updateByPrimaryKey(TCategory record);
}