package com.wtgroup.blog.entity;

public class TCategory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_category.id
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_category.category_name
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    private String categoryName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_category.alias_name
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    private String aliasName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_category.create_user
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    private Long createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_category.create_time
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    private Long createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_category.update_user
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    private Long updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_category.update_time
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    private Long updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_category.id
     *
     * @return the value of t_category.id
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_category.id
     *
     * @param id the value for t_category.id
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_category.category_name
     *
     * @return the value of t_category.category_name
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    public String getCategoryName() {
        return categoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_category.category_name
     *
     * @param categoryName the value for t_category.category_name
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName == null ? null : categoryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_category.alias_name
     *
     * @return the value of t_category.alias_name
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    public String getAliasName() {
        return aliasName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_category.alias_name
     *
     * @param aliasName the value for t_category.alias_name
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    public void setAliasName(String aliasName) {
        this.aliasName = aliasName == null ? null : aliasName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_category.create_user
     *
     * @return the value of t_category.create_user
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    public Long getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_category.create_user
     *
     * @param createUser the value for t_category.create_user
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    public void setCreateUser(Long createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_category.create_time
     *
     * @return the value of t_category.create_time
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_category.create_time
     *
     * @param createTime the value for t_category.create_time
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_category.update_user
     *
     * @return the value of t_category.update_user
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    public Long getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_category.update_user
     *
     * @param updateUser the value for t_category.update_user
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    public void setUpdateUser(Long updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_category.update_time
     *
     * @return the value of t_category.update_time
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    public Long getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_category.update_time
     *
     * @param updateTime the value for t_category.update_time
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    public void setUpdateTime(Long updateTime) {
        this.updateTime = updateTime;
    }
}