package com.wtgroup.blog.entity;

public class TResource {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resource.id
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resource.url
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resource.create_user
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    private Long createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resource.create_time
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    private Long createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resource.id
     *
     * @return the value of t_resource.id
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resource.id
     *
     * @param id the value for t_resource.id
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resource.url
     *
     * @return the value of t_resource.url
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resource.url
     *
     * @param url the value for t_resource.url
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resource.create_user
     *
     * @return the value of t_resource.create_user
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    public Long getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resource.create_user
     *
     * @param createUser the value for t_resource.create_user
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    public void setCreateUser(Long createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resource.create_time
     *
     * @return the value of t_resource.create_time
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resource.create_time
     *
     * @param createTime the value for t_resource.create_time
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }
}