package com.wtgroup.blog.entity;

public class TArticle {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article.id
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article.title
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article.fixed_link
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    private String fixedLink;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article.is_show
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    private Integer isShow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article.sort_value
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    private Integer sortValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article.category_id
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    private Integer categoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article.category_name
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    private String categoryName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article.create_user
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    private Long createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article.create_time
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    private Long createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article.update_user
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    private Long updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article.update_time
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    private Long updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article.id
     *
     * @return the value of t_article.id
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article.id
     *
     * @param id the value for t_article.id
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article.title
     *
     * @return the value of t_article.title
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article.title
     *
     * @param title the value for t_article.title
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article.fixed_link
     *
     * @return the value of t_article.fixed_link
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    public String getFixedLink() {
        return fixedLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article.fixed_link
     *
     * @param fixedLink the value for t_article.fixed_link
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    public void setFixedLink(String fixedLink) {
        this.fixedLink = fixedLink == null ? null : fixedLink.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article.is_show
     *
     * @return the value of t_article.is_show
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    public Integer getIsShow() {
        return isShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article.is_show
     *
     * @param isShow the value for t_article.is_show
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    public void setIsShow(Integer isShow) {
        this.isShow = isShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article.sort_value
     *
     * @return the value of t_article.sort_value
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    public Integer getSortValue() {
        return sortValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article.sort_value
     *
     * @param sortValue the value for t_article.sort_value
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    public void setSortValue(Integer sortValue) {
        this.sortValue = sortValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article.category_id
     *
     * @return the value of t_article.category_id
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article.category_id
     *
     * @param categoryId the value for t_article.category_id
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article.category_name
     *
     * @return the value of t_article.category_name
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    public String getCategoryName() {
        return categoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article.category_name
     *
     * @param categoryName the value for t_article.category_name
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName == null ? null : categoryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article.create_user
     *
     * @return the value of t_article.create_user
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    public Long getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article.create_user
     *
     * @param createUser the value for t_article.create_user
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    public void setCreateUser(Long createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article.create_time
     *
     * @return the value of t_article.create_time
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article.create_time
     *
     * @param createTime the value for t_article.create_time
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article.update_user
     *
     * @return the value of t_article.update_user
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    public Long getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article.update_user
     *
     * @param updateUser the value for t_article.update_user
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    public void setUpdateUser(Long updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article.update_time
     *
     * @return the value of t_article.update_time
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    public Long getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article.update_time
     *
     * @param updateTime the value for t_article.update_time
     *
     * @mbggenerated Fri Jan 26 01:48:50 CST 2018
     */
    public void setUpdateTime(Long updateTime) {
        this.updateTime = updateTime;
    }
}